/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as MeterReadingsRouteImport } from './routes/meter-readings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HelpRouteImport } from './routes/help'
import { Route as EnquiryRouteImport } from './routes/enquiry'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConsumersRouteImport } from './routes/consumers'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsRevenueRouteImport } from './routes/reports.revenue'
import { Route as ReportsCollectionRouteImport } from './routes/reports.collection'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTariffRouteImport } from './routes/admin.tariff'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'

const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const MeterReadingsRoute = MeterReadingsRouteImport.update({
  id: '/meter-readings',
  path: '/meter-readings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquiryRoute = EnquiryRouteImport.update({
  id: '/enquiry',
  path: '/enquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumersRoute = ConsumersRouteImport.update({
  id: '/consumers',
  path: '/consumers',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRevenueRoute = ReportsRevenueRouteImport.update({
  id: '/reports/revenue',
  path: '/reports/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsCollectionRoute = ReportsCollectionRouteImport.update({
  id: '/reports/collection',
  path: '/reports/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTariffRoute = AdminTariffRouteImport.update({
  id: '/admin/tariff',
  path: '/admin/tariff',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/admin/logs',
  path: '/admin/logs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/consumers': typeof ConsumersRoute
  '/dashboard': typeof DashboardRoute
  '/enquiry': typeof EnquiryRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/meter-readings': typeof MeterReadingsRoute
  '/payments': typeof PaymentsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/tariff': typeof AdminTariffRoute
  '/admin/users': typeof AdminUsersRoute
  '/reports/collection': typeof ReportsCollectionRoute
  '/reports/revenue': typeof ReportsRevenueRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/consumers': typeof ConsumersRoute
  '/dashboard': typeof DashboardRoute
  '/enquiry': typeof EnquiryRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/meter-readings': typeof MeterReadingsRoute
  '/payments': typeof PaymentsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/tariff': typeof AdminTariffRoute
  '/admin/users': typeof AdminUsersRoute
  '/reports/collection': typeof ReportsCollectionRoute
  '/reports/revenue': typeof ReportsRevenueRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/consumers': typeof ConsumersRoute
  '/dashboard': typeof DashboardRoute
  '/enquiry': typeof EnquiryRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/meter-readings': typeof MeterReadingsRoute
  '/payments': typeof PaymentsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/tariff': typeof AdminTariffRoute
  '/admin/users': typeof AdminUsersRoute
  '/reports/collection': typeof ReportsCollectionRoute
  '/reports/revenue': typeof ReportsRevenueRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billing'
    | '/consumers'
    | '/dashboard'
    | '/enquiry'
    | '/help'
    | '/login'
    | '/meter-readings'
    | '/payments'
    | '/admin/logs'
    | '/admin/tariff'
    | '/admin/users'
    | '/reports/collection'
    | '/reports/revenue'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billing'
    | '/consumers'
    | '/dashboard'
    | '/enquiry'
    | '/help'
    | '/login'
    | '/meter-readings'
    | '/payments'
    | '/admin/logs'
    | '/admin/tariff'
    | '/admin/users'
    | '/reports/collection'
    | '/reports/revenue'
  id:
    | '__root__'
    | '/'
    | '/billing'
    | '/consumers'
    | '/dashboard'
    | '/enquiry'
    | '/help'
    | '/login'
    | '/meter-readings'
    | '/payments'
    | '/admin/logs'
    | '/admin/tariff'
    | '/admin/users'
    | '/reports/collection'
    | '/reports/revenue'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillingRoute: typeof BillingRoute
  ConsumersRoute: typeof ConsumersRoute
  DashboardRoute: typeof DashboardRoute
  EnquiryRoute: typeof EnquiryRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  MeterReadingsRoute: typeof MeterReadingsRoute
  PaymentsRoute: typeof PaymentsRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminTariffRoute: typeof AdminTariffRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ReportsCollectionRoute: typeof ReportsCollectionRoute
  ReportsRevenueRoute: typeof ReportsRevenueRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meter-readings': {
      id: '/meter-readings'
      path: '/meter-readings'
      fullPath: '/meter-readings'
      preLoaderRoute: typeof MeterReadingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquiry': {
      id: '/enquiry'
      path: '/enquiry'
      fullPath: '/enquiry'
      preLoaderRoute: typeof EnquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumers': {
      id: '/consumers'
      path: '/consumers'
      fullPath: '/consumers'
      preLoaderRoute: typeof ConsumersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/revenue': {
      id: '/reports/revenue'
      path: '/reports/revenue'
      fullPath: '/reports/revenue'
      preLoaderRoute: typeof ReportsRevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/collection': {
      id: '/reports/collection'
      path: '/reports/collection'
      fullPath: '/reports/collection'
      preLoaderRoute: typeof ReportsCollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tariff': {
      id: '/admin/tariff'
      path: '/admin/tariff'
      fullPath: '/admin/tariff'
      preLoaderRoute: typeof AdminTariffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/admin/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillingRoute: BillingRoute,
  ConsumersRoute: ConsumersRoute,
  DashboardRoute: DashboardRoute,
  EnquiryRoute: EnquiryRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  MeterReadingsRoute: MeterReadingsRoute,
  PaymentsRoute: PaymentsRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminTariffRoute: AdminTariffRoute,
  AdminUsersRoute: AdminUsersRoute,
  ReportsCollectionRoute: ReportsCollectionRoute,
  ReportsRevenueRoute: ReportsRevenueRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
